level_0 = {
		'terrain': r'....\levels\0\level_0_terrain.csv',
		'coins':r'....\levels\0\level_0_coins.csv',
		'fg palms':r'....\levels\0\level_0_fg_palms.csv',
		'bg palms':r'....\levels\0\level_0_bg_palms.csv',
		'crates': r'....\levels\0\level_0_crates.csv',
		'enemies':r'....\levels\0\level_0_enemies.csv',
		'constraints':r'....\levels\0\level_0_constraints.csv',
		'player': r'....\levels\0\level_0_player.csv',
		'grass': r'....\levels\0\level_0_grass.csv',
		'node_pos': (110,400),
		'unlock': 1,
		'node_graphics': r'....\graphics\overworld\0'}
level_1 = {
		'terrain': r'....\levels\1\level_1_terrain.csv',
		'coins':r'....\levels\1\level_1_coins.csv',
		'fg palms':r'....\levels\1\level_1_fg_palms.csv',
		'bg palms':r'....\levels\1\level_1_bg_palms.csv',
		'crates': r'....\levels\1\level_1_crates.csv',
		'enemies':r'....\levels\1\level_1_enemies.csv',
		'constraints':r'....\levels\1\level_1_constraints.csv',
		'player': r'....\levels\1\level_1_player.csv',
		'grass': r'....\levels\1\level_1_grass.csv',
		'node_pos': (300,220),
		'node_graphics': r'....\graphics\overworld\1',
		'unlock': 2}
level_2 = {
		'terrain': r'....\levels\2\level_2_terrain.csv',
		'coins':r'....\levels\2\level_2_coins.csv',
		'fg palms':r'....\levels\2\level_2_fg_palms.csv',
		'bg palms':r'....\levels\2\level_2_bg_palms.csv',
		'crates': r'....\levels\2\level_2_crates.csv',
		'enemies':r'....\levels\2\level_2_enemies.csv',
		'constraints':r'....\levels\2\level_2_constraints.csv',
		'player': r'....\levels\2\level_2_player.csv',
		'grass': r'....\levels\2\level_2_grass.csv',
		'node_pos': (480,610),
		'node_graphics': r'....\graphics\overworld\2',
		'unlock': 3}
level_3 = {
		'terrain': r'....\levels\2\level_2_terrain.csv',
		'coins':r'....\levels\2\level_2_coins.csv',
		'fg palms':r'....\levels\2\level_2_fg_palms.csv',
		'bg palms':r'....\levels\2\level_2_bg_palms.csv',
		'crates': r'....\levels\2\level_2_crates.csv',
		'enemies':r'....\levels\2\level_2_enemies.csv',
		'constraints':r'....\levels\2\level_2_constraints.csv',
		'player': r'....\levels\2\level_2_player.csv',
		'grass': r'....\levels\2\level_2_grass.csv',
		'node_pos': (610,350),
		'node_graphics': r'....\graphics\overworld\3',
		'unlock': 4}
level_4 = {
		'terrain': r'....\levels\2\level_2_terrain.csv',
		'coins':r'....\levels\2\level_2_coins.csv',
		'fg palms':r'....\levels\2\level_2_fg_palms.csv',
		'bg palms':r'....\levels\2\level_2_bg_palms.csv',
		'crates': r'....\levels\2\level_2_crates.csv',
		'enemies':r'....\levels\2\level_2_enemies.csv',
		'constraints':r'....\levels\2\level_2_constraints.csv',
		'player': r'....\levels\2\level_2_player.csv',
		'grass': r'....\levels\2\level_2_grass.csv',
		'node_pos': (880,210),
		'node_graphics': r'....\graphics\overworld\4',
		'unlock': 5}
level_5 = {
		'terrain': r'....\levels\2\level_2_terrain.csv',
		'coins':r'....\levels\2\level_2_coins.csv',
		'fg palms':r'....\levels\2\level_2_fg_palms.csv',
		'bg palms':r'....\levels\2\level_2_bg_palms.csv',
		'crates': r'....\levels\2\level_2_crates.csv',
		'enemies':r'....\levels\2\level_2_enemies.csv',
		'constraints':r'....\levels\2\level_2_constraints.csv',
		'player': r'....\levels\2\level_2_player.csv',
		'grass': r'....\levels\2\level_2_grass.csv',
		'node_pos': (1050,400),
		'node_graphics':r'....\graphics\overworld\5',
		'unlock': 5}

levels = {
	0: level_0,
	1: level_1,
	2: level_2,
	3: level_3,
	4: level_4,
	5: level_5}